apiVersion: apps/v1
kind: Deployment
metadata:
  name: peliculas-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: peliculas-api
  template:
    metadata:
      labels:
        app: peliculas-api
    spec:
      containers:
      - name: peliculas-api
        image: gcr.io/helpful-pixel-377204/myimage:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: stip
        - name: DB_PASS
          value: holaquemas
        - name: DB_NAME
          value: test1
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://$(DB_USER):$(DB_PASS)@postgres-service:$(DB_PORT)/$(DB_NAME)"
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASS)@postgres-service:$(DB_PORT)/$(DB_NAME)"
