version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ejemplo_api_peliculas2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "flask db upgrade && flask run --host=0.0.0.0"
    volumes:
      - .:/api-peliculas
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "entrypoint:app"
      FLASK_ENV: "development"
      APP_SETTINGS_MODULE: "config.default"
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: "postgresql://postgres:root@db/ejemplo_api_peliculas2"
    depends_on:
      - db

volumes:
  postgres_data:
